from django.core.management.base import BaseCommand
from core.models import Categoria, Subcategoria, Producto


class Command(BaseCommand):
    help = 'Pobla la base de datos con los 87 productos del catálogo ElectriPorc'

    def handle(self, *args, **options):
        # Limpiar productos existentes
        Producto.objects.all().delete()
        Subcategoria.objects.all().delete()
        Categoria.objects.all().delete()

        # =============================================
        # CREAR CATEGORÍAS
        # =============================================
        cats = {}
        categorias_data = [
            ('ALIMENTACION', 'ALIMENTACIÓN', 'Sistemas de comederos, dosificadores y componentes para la alimentación automatizada en granjas porcinas.', '001'),
            ('SILOS_ALMACENAMIENTO', 'SILOS Y ALMACENAMIENTO', 'Silos galvanizados, elevadores y accesorios para el almacenamiento seguro de alimento.', '002'),
            ('MATERIALES_AUTOMATIZAR', 'MATERIALES PARA AUTOMATIZAR', 'Sistemas de transporte de alimento y pesaje para automatización en granjas.', '003'),
            ('MOTORES_REDUCTORES', 'MOTORES Y REDUCTORES', 'Motorreductores y cajas reductoras para sistemas de alimentación y agitación.', '004'),
            ('PRODUCCION_PORCINA', 'PRODUCCIÓN PORCINA', 'Bebederos, jaulas, slats, corrales y equipos para la producción porcina.', '005'),
            ('REPUESTOS_ACCESORIOS', 'REPUESTOS Y ACCESORIOS', 'Repuestos, tornillería y accesorios para mantenimiento de equipos porcícolas.', '006'),
            ('EQUIPOS_COMPLEMENTARIOS', 'EQUIPOS COMPLEMENTARIOS', 'Criadoras, lámparas, tejas, carrillos y equipos complementarios para granjas.', '007'),
        ]

        for key, nombre, desc, orden in categorias_data:
            cats[key] = Categoria.objects.create(
                nombre=nombre,
                slug=nombre.lower().replace(' ', '-').replace('á', 'a').replace('é', 'e').replace('í', 'i').replace('ó', 'o').replace('ú', 'u'),
                descripcion=desc,
                descripcion_corta=desc[:100],
                orden=int(orden),
                activa=True
            )

        # =============================================
        # CREAR SUBCATEGORÍAS
        # =============================================
        subs = {}
        subcats_data = [
            ('comederos_papilleros', cats['ALIMENTACION'], 'Comederos y Papilleros', '001'),
            ('componentes_alimentacion', cats['ALIMENTACION'], 'Componentes para sistema de alimentación', '002'),
            ('sistemas_automaticos', cats['ALIMENTACION'], 'Sistemas automáticos', '003'),
            ('silos_galvanizados', cats['SILOS_ALMACENAMIENTO'], 'Silos galvanizados', '004'),
            ('elevador_silos', cats['SILOS_ALMACENAMIENTO'], 'Elevador de alimento para silos', '005'),
            ('accesorios_silos', cats['SILOS_ALMACENAMIENTO'], 'Accesorios para Silos', '006'),
            ('transporte_alimento', cats['MATERIALES_AUTOMATIZAR'], 'Sistema de transporte de alimento', '007'),
            ('sistema_pesaje', cats['MATERIALES_AUTOMATIZAR'], 'Sistema de pesaje', '008'),
            ('bebederos', cats['PRODUCCION_PORCINA'], 'Bebederos', '009'),
            ('jaulas_maternidad_gestacion', cats['PRODUCCION_PORCINA'], 'Jaulas de maternidad y gestación', '010'),
            ('plaquetas_lechon_madre', cats['PRODUCCION_PORCINA'], 'Plaquetas para lechón y madre', '011'),
            ('slats_fibra_vidrio', cats['PRODUCCION_PORCINA'], 'Slats en fibra de vidrio', '012'),
            ('corrales_paneles_puertas', cats['PRODUCCION_PORCINA'], 'Corrales, paneles en PVC y puertas', '013'),
            ('corrales_divisiones_puertas', cats['PRODUCCION_PORCINA'], 'Corrales, divisiones y puertas', '014'),
            ('comedero_dosificador', cats['REPUESTOS_ACCESORIOS'], 'Para comedero y dosificador', '015'),
            ('automatizacion_repuestos', cats['REPUESTOS_ACCESORIOS'], 'Para automatización', '016'),
            ('tornilleria_accesorios', cats['REPUESTOS_ACCESORIOS'], 'Tornillería y accesorios', '017'),
        ]

        for key, cat, nombre, orden in subcats_data:
            subs[key] = Subcategoria.objects.create(
                categoria=cat,
                nombre=nombre,
                slug=nombre.lower().replace(' ', '-').replace('á', 'a').replace('é', 'e').replace('í', 'i').replace('ó', 'o').replace('ú', 'u'),
                orden=int(orden),
                activa=True
            )

        # =============================================
        # CREAR PRODUCTOS
        # =============================================
        productos = [
            # ===========================================
            # ALIMENTACIÓN - Comederos y Papilleros (001-011)
            # ===========================================
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero ceba seco-húmedo',
                'slug': 'comedero-ceba-seco-humedo',
                'orden': 1,
                'descripcion_corta': 'Dispensación de alimento concentrado en harina o peletizado, para ceba.',
                'descripcion': 'Dispensación de alimento concentrado en harina o peletizado, para ceba.',
                'materiales': 'Estructura en acero galvanizado en caliente. Bandeja en acero inoxidable.',
                'capacidad': '140 L. Capacidad de alimento: 80 kg. Alimenta 50 cerdos gordos.',
                'regulacion': '20 puntos de regulación de alimento.',
                'componentes': 'Perilla con pin metálico. Tubería de agua. Válvula automática para control de nivel de agua.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero seco y húmedo para ceba',
                'slug': 'comedero-seco-humedo-ceba',
                'orden': 2,
                'descripcion_corta': 'Comedero diseñado para cerdos de ceba, con sistema de alimentación seca o húmeda que mejora el consumo y reduce el desperdicio de alimento.',
                'descripcion': 'Comedero diseñado para cerdos de ceba, con sistema de alimentación seca o húmeda que mejora el consumo y reduce el desperdicio de alimento.',
                'capacidad': '100 kg.',
                'dimensiones': '76 × 60 × 120 cm.',
                'materiales': 'Tolva en plástico de alta resistencia, estructura galvanizada y plato redondo en acero inoxidable.',
                'regulacion': 'Regulación del flujo de alimento.',
                'aplicaciones': 'Ideal para cerdos en etapa de ceba (crecimiento y finalización). Recomendado para granjas porcícolas de producción intensiva. Apto para sistemas de alimentación seca o húmeda.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero ceba doble cara',
                'slug': 'comedero-ceba-doble-cara',
                'orden': 3,
                'descripcion_corta': 'Comedero ajustable de doble cara, con 8 bocas y sistema seco-húmedo. Fabricado para la etapa de ceba y apto para sistemas wean-to-finish.',
                'descripcion': 'Comedero ajustable de doble cara, con 8 bocas y sistema seco-húmedo. Fabricado para la etapa de ceba y apto para sistemas wean-to-finish.',
                'capacidad': '100 kg. Alimenta entre 70 y 80 cerdos en ceba.',
                'dimensiones': '124 cm de largo × 50 cm de ancho × 90 cm de alto.',
                'materiales': 'Acero inoxidable de alto calibre 304.',
                'regulacion': 'Comedero regulable en 8 puntos para evitar desperdicio de alimento. Calibre de la lámina: 1.2 mm.',
                'componentes': 'Cada orificio de alimentación mide 36 cm de ancho. Cuenta con boquillas de agua integradas, lo que permite que los cerdos beban agua limpia mientras se alimentan y aumenta notablemente el consumo.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero precebo seco-húmedo',
                'slug': 'comedero-precebo-seco-humedo',
                'orden': 4,
                'descripcion_corta': 'Comedero seco-húmedo para la etapa de precebo.',
                'descripcion': 'Comedero seco-húmedo para la etapa de precebo.',
                'capacidad': 'Tolva de 65 L. Capacidad de alimento: 40 kg. Alimenta hasta 50 lechones por corral.',
                'dimensiones': '96 cm de alto × 46 cm de diámetro.',
                'materiales': 'Estructura en acero galvanizado al caliente. Bandeja en acero inoxidable.',
                'regulacion': '20 puntos de regulación de alimento.',
                'componentes': 'Perilla con pin metálico. Tubería para agua.',
                'especificaciones': 'Peso: 20 kg.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero doble cara inoxidable precebo',
                'slug': 'comedero-doble-cara-inoxidable-precebo',
                'orden': 5,
                'descripcion_corta': 'Comedero ajustable de dos caras en acero inoxidable, 10 bocas.',
                'descripcion': 'Comedero ajustable de dos caras en acero inoxidable, 10 bocas.',
                'capacidad': '50 kg. Alimenta hasta 50 cerdos en precebo.',
                'dimensiones': '97.5 cm de largo × 46 cm de ancho × 61 cm de alto.',
                'materiales': 'Acero inoxidable de alto calibre.',
                'regulacion': 'Comedero regulable en 12 puntos para evitar desperdicio de alimento. Calibre de la lámina: 1.2 mm.',
                'componentes': 'Bandeja con esquinas redondeadas para que no se acumule el alimento y facilitar la limpieza.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero segunda edad',
                'slug': 'comedero-segunda-edad',
                'orden': 6,
                'descripcion_corta': 'Comedero plástico para la segunda edad de los lechones.',
                'descripcion': 'Comedero plástico para la segunda edad de los lechones.',
                'capacidad': '17 kg. Capacidad para alimentar 30 lechones.',
                'dimensiones': 'Alto: 63 cm. Ancho: 44 cm.',
                'materiales': 'Plástico de alta calidad.',
                'especificaciones': 'Peso: 2.78 kg. Puestos: 10. Niveles de regulación: 7.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero verde redondo',
                'slug': 'comedero-verde-redondo',
                'orden': 7,
                'descripcion_corta': 'Comedero redondo para etapa de precebo, cero desperdicio.',
                'descripcion': 'Comedero redondo para etapa de precebo, cero desperdicio.',
                'capacidad': 'Hasta 5 kilos. Capacidad para alimentar 20 lechones.',
                'materiales': 'Polipropileno de alta densidad.',
                'componentes': '8 compartimientos. Ancho por compartimiento: 15 cm.',
                'aplicaciones': 'Ideal para la etapa de precebo.',
                'beneficios': 'Cero desperdicio.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero madre paridera con refuerzo',
                'slug': 'comedero-madre-paridera-refuerzo',
                'orden': 8,
                'descripcion_corta': 'Comedero ideal para madres en paridera, con refuerzo en acero inoxidable.',
                'descripcion': 'Comedero ideal para madres en paridera, con refuerzo en acero inoxidable.',
                'dimensiones': '36 × 27 cm.',
                'materiales': 'Polietileno de alta densidad y refuerzo en acero inoxidable.',
                'componentes': 'Diseño ergonómico. Alta resistencia. Fácil mantenimiento. Evita acumulación de residuos.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Comedero madre paridera en acero inoxidable',
                'slug': 'comedero-madre-paridera-inoxidable',
                'orden': 9,
                'descripcion_corta': 'Comedero de acero inoxidable 304 para cerdas. Higiénico, resistente y fácil de limpiar.',
                'descripcion': 'Comedero de acero inoxidable 304 para cerdas. Higiénico, resistente y fácil de limpiar. Aumenta la eficiencia alimenticia en granjas porcinas.',
                'dimensiones': '37 cm de altura × 45 cm de ancho.',
                'materiales': 'Acero inoxidable 304.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Papillero inoxidable',
                'slug': 'papillero-inoxidable',
                'orden': 10,
                'descripcion_corta': 'Ideal para iniciar el alimento en papilla o sólido en las parideras.',
                'descripcion': 'Ideal para iniciar el alimento en papilla o sólido en las parideras.',
                'capacidad': '10 a 20 lechones.',
                'materiales': 'Acero inoxidable de alta resistencia.',
                'componentes': '4 separadores.',
                'beneficios': 'Fácil de limpiar. Minimiza el desperdicio.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'comederos_papilleros',
                'nombre': 'Papillero Turbo Pig',
                'slug': 'papillero-turbo-pig',
                'orden': 11,
                'descripcion_corta': 'Comedero redondo para lactancia, se fija en cualquier tipo de piso de rejilla.',
                'descripcion': 'Fabricado con plástico 100% virgen y aditivos que le otorgan una alta resistencia y durabilidad. Se fija en cualquier tipo de piso de rejilla: plástico, metal o liso de concreto. Complementa la alimentación durante la etapa de la lactancia y favorece a que el lechón inicie su etapa de alimentación sólida, probando en cualquiera de sus espacios diferentes tipos de alimentos y aditivos.',
                'materiales': 'Plástico 100% virgen y aditivos.',
                'componentes': 'Consta de comedero redondo, manija triangular con flecha de dirección, varilla de acero inoxidable, tubo de plástico, resorte y tornillería.',
                'beneficios': 'Mayor peso de la camada. Mejor uniformidad de la camada. Disminución en la conversión alimenticia. Ayuda en la disminución de la mortalidad. Superficies lisas y redondeadas para fácil lavado y desinfección.',
            },

            # ===========================================
            # ALIMENTACIÓN - Componentes para sistema de alimentación (012-016)
            # ===========================================
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'componentes_alimentacion',
                'nombre': 'Dosificador verde y rojo',
                'slug': 'dosificador-verde-rojo',
                'orden': 12,
                'descripcion_corta': 'Dosificador de 6 L para dispensar porciones específicas de alimento.',
                'descripcion': 'Estos dosificadores están diseñados para dispensar porciones específicas de alimento a la medida requerida para cada cerdo.',
                'capacidad': '6 L.',
                'materiales': 'Polipropileno 100%.',
                'componentes': 'Cubo transparente para una fácil observación. Contiene bola de control de cantidad. Automatiza el transporte del alimento para ahorrar mano de obra.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'componentes_alimentacion',
                'nombre': 'Dosificador de alimento',
                'slug': 'dosificador-alimento',
                'orden': 13,
                'descripcion_corta': 'Dosificador de 8 L para dispensar porciones específicas de alimento.',
                'descripcion': 'Estos dosificadores están diseñados para dispensar porciones específicas de alimento a la medida requerida para cada cerdo.',
                'capacidad': '8 L.',
                'materiales': 'Polipropileno 100%.',
                'componentes': 'Cubo transparente para una fácil observación. Contiene bola de control de cantidad. Automatiza el transporte del alimento para ahorrar mano de obra.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'componentes_alimentacion',
                'nombre': 'Bocas descarga',
                'slug': 'bocas-descarga',
                'orden': 14,
                'descripcion_corta': 'Bocas de descarga en plástico de alta resistencia para tubería de 60 mm y 75 mm.',
                'descripcion': 'Bocas de descarga fabricadas en plástico de alta resistencia, diseñadas para garantizar una descarga eficiente del alimento y una conexión segura con el sistema de transporte.',
                'materiales': 'Plástico de alta resistencia.',
                'componentes': 'Disponibles para tubería de 60 mm y 75 mm. Alta resistencia al desgaste y a la corrosión. Fácil instalación y reemplazo. Compatibles con sistemas de alimentación automática para granjas.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'componentes_alimentacion',
                'nombre': 'Tolva automática para jaula',
                'slug': 'tolva-automatica-jaula',
                'orden': 15,
                'descripcion_corta': 'Tolva automática con sistema dosificador para jaulas.',
                'descripcion': 'Tolva automática con sistema dosificador para jaulas.',
                'capacidad': '8 kg.',
                'dimensiones': '48 × 37 cm.',
                'materiales': 'Acero inoxidable y plástico de alta densidad.',
                'regulacion': '6 posiciones.',
                'componentes': 'Sistema dosificador. Fácil de instalar.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'componentes_alimentacion',
                'nombre': 'Tolva semiautomática',
                'slug': 'tolva-semiautomatica',
                'orden': 16,
                'descripcion_corta': 'Tolva con sistema de boya que regula el nivel de alimento de forma automática.',
                'descripcion': 'Tolva diseñada para el suministro manual de alimento, equipada con sistema de boya que regula el nivel de alimento de forma automática dentro del comedero, reduciendo desperdicios y garantizando un suministro continuo.',
                'materiales': 'Plástico de alta resistencia.',
                'componentes': 'Sistema de boya para control automático del nivel de alimento.',
                'beneficios': 'Reduce el desperdicio de alimento. Fácil instalación y limpieza. Material resistente a la corrosión y a la humedad. Diseño higiénico y de larga duración. Bajo mantenimiento.',
                'aplicaciones': 'Maternidad. Precebo. Destete. Corrales individuales. Sistemas de alimentación manual.',
            },

            # ===========================================
            # ALIMENTACIÓN - Sistemas automáticos (017-018)
            # ===========================================
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'sistemas_automaticos',
                'nombre': 'Sensor de paro con lengüeta',
                'slug': 'sensor-paro-lengueta',
                'orden': 17,
                'descripcion_corta': 'Control automático de nivel de alimento para llenado o vaciado.',
                'descripcion': 'Permite controlar automáticamente el nivel de alimento, activando o desactivando bombas, alarmas o sistemas de llenado y vaciado. Fabricado con materiales resistentes para un funcionamiento confiable en ambientes exigentes.',
                'materiales': 'Polipropileno de alta durabilidad.',
                'componentes': 'Cable de alta resistencia e impermeable.',
                'especificaciones': 'Control automático de nivel de alimento. Función para llenado o vaciado. Compatible con aguas limpias, aguas residuales y purines. Larga vida útil y alta confiabilidad.',
            },
            {
                'categoria': 'ALIMENTACION',
                'subcategoria': 'sistemas_automaticos',
                'nombre': 'Sensor de proximidad inductivo',
                'slug': 'sensor-proximidad-inductivo',
                'orden': 18,
                'descripcion_corta': 'Sensor electrónico para detectar la presencia de objetos sin contacto físico.',
                'descripcion': 'Sensor electrónico diseñado para detectar la presencia de objetos sin necesidad de contacto físico. Ideal para sistemas automatizados, proporcionando una detección precisa y confiable en ambientes industriales.',
                'materiales': 'Carcasa metálica de alta resistencia.',
                'componentes': '4 cables: 2 para alimentación de 24 voltios; los otros 2 son de contacto cerrado y otro contacto abierto.',
                'especificaciones': 'Detección sin contacto de objetos metálicos. Alta precisión y respuesta rápida. Fácil instalación mediante rosca y tuercas de fijación. Alta resistencia a vibraciones y golpes. Bajo mantenimiento. Ideal para ambientes agropecuarios. Larga vida útil.',
            },

            # ===========================================
            # SILOS Y ALMACENAMIENTO - Silos galvanizados (019)
            # ===========================================
            {
                'categoria': 'SILOS_ALMACENAMIENTO',
                'subcategoria': 'silos_galvanizados',
                'nombre': 'Silo galvanizado para almacenamiento',
                'slug': 'silo-galvanizado-almacenamiento',
                'orden': 19,
                'descripcion_corta': 'Silo de acero galvanizado para almacenamiento seguro de alimento balanceado.',
                'descripcion': 'Silo fabricado en acero galvanizado de alta resistencia, diseñado para el almacenamiento seguro de alimento balanceado. Su estructura garantiza protección del producto, fácil carga y descarga, y una larga vida útil en ambientes de producción.',
                'capacidad': 'Capacidades disponibles: 8, 10, 14, 18 y 22 toneladas.',
                'materiales': 'Acero galvanizado.',
                'componentes': 'Diseño cónico para una descarga eficiente del alimento. Escalera y plataforma de acceso para inspección y mantenimiento. Alta resistencia a la corrosión y a la intemperie. Fácil instalación y mantenimiento.',
                'aplicaciones': 'Granjas porcinas y ganaderas. Sistemas de alimentación automatizada.',
            },

            # ===========================================
            # SILOS Y ALMACENAMIENTO - Elevador de alimento para silos (020)
            # ===========================================
            {
                'categoria': 'SILOS_ALMACENAMIENTO',
                'subcategoria': 'elevador_silos',
                'nombre': 'Transporte eficiente para silos',
                'slug': 'transporte-eficiente-silos',
                'orden': 20,
                'descripcion_corta': 'Elevador de alimento con sistema sinfín para carga de silos.',
                'descripcion': 'Elevador de alimento diseñado para transportar granos y alimento balanceado de forma eficiente hacia silos o sistemas de almacenamiento. Su estructura robusta garantiza un funcionamiento seguro, continuo y de alta durabilidad.',
                'materiales': 'Sistema de transporte: Sinfín. Operación: Accionamiento mediante motorreductor.',
                'componentes': 'Diseño portátil para facilitar su traslado y ubicación. Bajo mantenimiento y fácil operación.',
                'aplicaciones': 'Carga de silos de almacenamiento. Transporte de alimento balanceado. Granjas porcinas y ganaderas.',
            },

            # ===========================================
            # SILOS Y ALMACENAMIENTO - Accesorios para Silos (021-026)
            # ===========================================
            {
                'categoria': 'SILOS_ALMACENAMIENTO',
                'subcategoria': 'accesorios_silos',
                'nombre': 'Salida de silo inoxidable',
                'slug': 'salida-silo-inoxidable',
                'orden': 21,
                'descripcion_corta': 'Salida de silo en acero inoxidable para flujo uniforme del alimento.',
                'descripcion': 'Salida de silo fabricada en acero inoxidable de alta resistencia, diseñada para garantizar un flujo uniforme del alimento desde el silo hacia el sistema de transporte o alimentación.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Alta resistencia a la corrosión y al desgaste. Diseño cónico para un flujo eficiente del alimento. Instalación mediante brida con perforaciones para una fijación segura. Fácil limpieza y mantenimiento.',
                'aplicaciones': 'Sistemas de almacenamiento de alimento en granjas porcinas y ganaderas. Compatible con sistemas de transporte por sinfín y alimentación automatizada.',
            },
            {
                'categoria': 'SILOS_ALMACENAMIENTO',
                'subcategoria': 'accesorios_silos',
                'nombre': 'Salida de silo transparente',
                'slug': 'salida-silo-transparente',
                'orden': 22,
                'descripcion_corta': 'Salida de silo en policarbonato transparente para inspección visual.',
                'descripcion': 'Salida de silo fabricada en policarbonato transparente de alta resistencia, diseñada para facilitar el flujo del alimento y permitir la inspección visual del nivel y paso del material.',
                'materiales': 'Policarbonato transparente.',
                'componentes': 'Alta resistencia a impactos y al desgaste. Permite visualizar el flujo del alimento. Diseño ligero y de fácil instalación. Fácil limpieza y mantenimiento.',
                'aplicaciones': 'Sistemas de almacenamiento y alimentación automatizada en granjas porcinas y ganaderas.',
            },
            {
                'categoria': 'SILOS_ALMACENAMIENTO',
                'subcategoria': 'accesorios_silos',
                'nombre': 'Cajetín doble de 60 mm',
                'slug': 'cajetin-doble-60mm',
                'orden': 23,
                'descripcion_corta': 'Cajetín doble en acero inoxidable para distribuir alimento a dos líneas de 60 mm.',
                'descripcion': 'Cajetín doble fabricado en acero inoxidable, diseñado para distribuir el alimento hacia dos líneas de transporte de 60 mm, garantizando un flujo eficiente y una alta durabilidad.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Diámetro de salida: 60 mm. Configuración: Doble salida. Alta resistencia a la corrosión y al desgaste. Fácil limpieza y mantenimiento.',
                'aplicaciones': 'Sistemas de alimentación automatizada para granjas porcinas y ganaderas.',
            },
            {
                'categoria': 'SILOS_ALMACENAMIENTO',
                'subcategoria': 'accesorios_silos',
                'nombre': 'Cajetín de 60 mm',
                'slug': 'cajetin-60mm',
                'orden': 24,
                'descripcion_corta': 'Cajetín en acero inoxidable para línea de transporte de 60 mm.',
                'descripcion': 'Cajetín fabricado en acero inoxidable, diseñado para recibir y conducir el alimento hacia una línea de transporte de 60 mm, garantizando un flujo eficiente y una excelente resistencia para uso continuo.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Diámetro de salida: 60 mm. Configuración: Salida sencilla. Alta resistencia a la corrosión y al desgaste. Fácil limpieza y mantenimiento.',
                'aplicaciones': 'Sistemas de alimentación automatizada para granjas porcinas y ganaderas.',
            },
            {
                'categoria': 'SILOS_ALMACENAMIENTO',
                'subcategoria': 'accesorios_silos',
                'nombre': 'Cajetín de 75 mm con rasera',
                'slug': 'cajetin-75mm-rasera',
                'orden': 25,
                'descripcion_corta': 'Cajetín en acero inoxidable con rasera de cierre para línea de 75 mm.',
                'descripcion': 'Cajetín fabricado en acero inoxidable, equipado con rasera de cierre para controlar el paso del alimento hacia la línea de transporte de 75 mm, permitiendo una operación segura y un mantenimiento sencillo.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Diámetro de salida: 75 mm. Incluye: Rasera de cierre manual. Alta resistencia a la corrosión y al desgaste. Fácil limpieza y mantenimiento.',
                'aplicaciones': 'Sistemas de alimentación automatizada para granjas porcinas y ganaderas.',
            },
            {
                'categoria': 'SILOS_ALMACENAMIENTO',
                'subcategoria': 'accesorios_silos',
                'nombre': 'Unidad de control',
                'slug': 'unidad-control',
                'orden': 26,
                'descripcion_corta': 'Unidad de control para gestionar el suministro automático de alimento en sistemas de sinfín y cadena.',
                'descripcion': 'Unidad de control diseñada para gestionar el suministro automático de alimento en sistemas de sinfín y reenvíos en sistemas de cadena. Su funcionamiento permite controlar el flujo de alimento de forma eficiente, garantizando una distribución continua y segura dentro de la granja.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Fácil instalación. Resistente a la corrosión.',
                'beneficios': 'Automatiza la distribución de alimento. Optimiza el funcionamiento del sistema.',
            },

            # ===========================================
            # MATERIALES PARA AUTOMATIZAR - Sistema de transporte (027-034)
            # ===========================================
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'transporte_alimento',
                'nombre': 'Máquina de arrastre',
                'slug': 'maquina-arrastre',
                'orden': 27,
                'descripcion_corta': 'Máquina de arrastre para sistemas de alimentación por cadena.',
                'descripcion': 'Máquina de arrastre diseñada para accionar sistemas de alimentación por cadena, garantizando un transporte continuo, eficiente y uniforme del alimento en instalaciones pecuarias.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Visor transparente para inspección del funcionamiento. Diseño robusto para trabajo continuo. Fácil acceso para limpieza y mantenimiento.',
                'especificaciones': 'Sistema de transmisión: Arrastre por cadena.',
            },
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'transporte_alimento',
                'nombre': 'Sinfín',
                'slug': 'sinfin',
                'orden': 28,
                'descripcion_corta': 'Sinfín flexible para transporte de alimento en sistemas automatizados.',
                'descripcion': 'Sinfín flexible diseñado para el transporte eficiente de alimento en sistemas de alimentación automatizada. Fabricado en acero de alta resistencia para garantizar un flujo continuo y una larga vida útil.',
                'materiales': 'Acero de alta resistencia.',
                'componentes': 'Diseño: Espiral flexible. Alta resistencia al desgaste. Funcionamiento continuo y uniforme. Compatible con sistemas de alimentación automatizada.',
                'especificaciones': 'Disponible en diferentes diámetros y longitudes, según el requerimiento del sistema.',
            },
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'transporte_alimento',
                'nombre': 'Cadena eslabonada',
                'slug': 'cadena-eslabonada',
                'orden': 29,
                'descripcion_corta': 'Cadena de alta resistencia con discos de arrastre para transporte de alimento.',
                'descripcion': 'Cadena eslabonada de alta resistencia, diseñada para el transporte eficiente de alimento en sistemas de alimentación automatizada. Incorpora discos de arrastre que garantizan un desplazamiento uniforme del alimento a lo largo de la línea.',
                'materiales': 'Cadena: Acero galvanizado de alta resistencia. Discos: Plástico técnico de alta durabilidad.',
                'componentes': 'Alta resistencia al desgaste y a la corrosión. Funcionamiento silencioso y de larga vida útil. Fácil instalación y mantenimiento.',
            },
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'transporte_alimento',
                'nombre': 'Corner azul',
                'slug': 'corner-azul',
                'orden': 30,
                'descripcion_corta': 'Corner en plástico de alta resistencia para cambios de dirección en sistemas de alimentación.',
                'descripcion': 'Corner fabricado en plástico de alta resistencia, diseñado para cambiar la dirección del sistema de alimentación por cadena o cable, garantizando un desplazamiento suave y continuo del alimento con mínimo desgaste de los componentes.',
                'materiales': 'Plástico técnico de alta resistencia.',
                'componentes': 'Color: Azul. Alta resistencia al desgaste, la corrosión y la humedad. Rodamiento central para un funcionamiento eficiente. Fácil instalación y bajo mantenimiento.',
                'aplicaciones': 'Cambios de dirección en líneas de alimentación.',
            },
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'transporte_alimento',
                'nombre': 'Corner en acero inoxidable',
                'slug': 'corner-acero-inoxidable',
                'orden': 31,
                'descripcion_corta': 'Corner en acero inoxidable con polea interna para sistemas de alimentación.',
                'descripcion': 'Corner fabricado en acero inoxidable de alta resistencia, diseñado para realizar cambios de dirección en sistemas de alimentación automatizada por cadena o cable. Su polea interna garantiza un desplazamiento suave, reduciendo el desgaste y mejorando la eficiencia del sistema.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Polea interna de alta resistencia. Rodamiento de precisión para un funcionamiento suave. Alta resistencia a la corrosión y al desgaste. Diseño desmontable para facilitar la limpieza y el mantenimiento.',
                'aplicaciones': 'Sistemas de alimentación automatizada para granjas porcinas. Cambios de dirección en líneas de transporte de alimento.',
            },
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'transporte_alimento',
                'nombre': 'Unión transparente',
                'slug': 'union-transparente',
                'orden': 32,
                'descripcion_corta': 'Unión en policarbonato transparente para inspección visual de la cadena.',
                'descripcion': 'Diseñada para conectar y permitir la inspección visual de la cadena en sistemas de alimentación automatizada. Su diseño facilita el monitoreo del funcionamiento del sistema sin necesidad de desmontar los componentes.',
                'materiales': 'Policarbonato transparente de alta resistencia.',
                'componentes': 'Alta resistencia al impacto y al desgaste. Permite la inspección visual del paso de la cadena y los discos. Fácil instalación y desmontaje. Compatible con sistemas de alimentación por cadena.',
                'aplicaciones': 'Inspección y mantenimiento de líneas de alimentación.',
            },
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'transporte_alimento',
                'nombre': 'Unión en acero inoxidable',
                'slug': 'union-acero-inoxidable',
                'orden': 33,
                'descripcion_corta': 'Unión en acero inoxidable para conectar tramos de tubería.',
                'descripcion': 'Unión fabricada en acero inoxidable, diseñada para conectar de forma segura los tramos de tubería en sistemas de alimentación automatizada. Su diseño proporciona un ensamble firme, garantizando la continuidad del transporte del alimento.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Alta resistencia a la corrosión y al desgaste. Unión segura mediante tornillería de fijación. Fácil instalación y desmontaje. Larga vida útil en ambientes de producción.',
                'aplicaciones': 'Conexión de tuberías para transporte de alimento.',
            },
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'transporte_alimento',
                'nombre': 'Bajante para sistema de alimentación',
                'slug': 'bajante-sistema-alimentacion',
                'orden': 34,
                'descripcion_corta': 'Bajante en acero galvanizado para conducir alimento desde la línea de transporte.',
                'descripcion': 'Bajante fabricado en acero galvanizado, diseñado para conducir el alimento desde la línea de transporte hasta los puntos de descarga de forma eficiente y segura. Su diseño facilita un flujo continuo del alimento y una instalación sencilla.',
                'materiales': 'Acero galvanizado.',
                'componentes': 'Alta resistencia a la corrosión y al desgaste. Diseño con ángulo de descarga para un flujo uniforme del alimento. Fácil instalación en sistemas de alimentación automatizada. Fabricado para una larga vida útil.',
            },

            # ===========================================
            # MATERIALES PARA AUTOMATIZAR - Sistema de pesaje (035)
            # ===========================================
            {
                'categoria': 'MATERIALES_AUTOMATIZAR',
                'subcategoria': 'sistema_pesaje',
                'nombre': 'Kit de básculas para silo',
                'slug': 'kit-basculas-silo',
                'orden': 35,
                'descripcion_corta': 'Sistema de pesaje para silos de almacenamiento de alimento.',
                'descripcion': 'Sistema de pesaje diseñado para silos de almacenamiento de alimento en granjas porcinas, permitiendo el monitoreo preciso del inventario y el consumo de alimento en tiempo real.',
                'materiales': 'Celdas de carga de alta precisión en acero aleado o acero inoxidable.',
                'componentes': 'Disponible en configuración de 4 celdas y 6 celdas de carga. Caja de conexiones para integración de señales. Indicador digital de peso de fácil lectura. Cableado de alta resistencia para exteriores. Protección contra humedad y polvo.',
                'especificaciones': 'Compatible con sistemas de automatización y monitoreo. Instalación sobre la estructura del silo sin afectar su funcionamiento.',
            },

            # ===========================================
            # MOTORES Y REDUCTORES (036-040)
            # ===========================================
            {
                'categoria': 'MOTORES_REDUCTORES',
                'subcategoria': None,
                'nombre': 'Motorreductor para sistema por espiral',
                'slug': 'motorreductor-espiral',
                'orden': 36,
                'descripcion_corta': 'Motorreductor para sistemas de alimentación por espiral (sinfín).',
                'descripcion': 'Motorreductor diseñado para accionar sistemas de alimentación por espiral (sinfín), proporcionando una transmisión de potencia eficiente, segura y continua para el transporte automático de alimento en granjas.',
                'materiales': 'Carcasa del motor en aluminio de alta resistencia.',
                'componentes': 'Relación de reducción: 5:1. Motor monofásico de 2 HP. Velocidad: 1,800 RPM. Funcionamiento confiable y de bajo mantenimiento. Compatible con sistemas automáticos de alimentación por espiral.',
            },
            {
                'categoria': 'MOTORES_REDUCTORES',
                'subcategoria': None,
                'nombre': 'Motorreductor para sistema de cadena',
                'slug': 'motorreductor-cadena',
                'orden': 37,
                'descripcion_corta': 'Motorreductor para sistemas de alimentación por cadena.',
                'descripcion': 'Motorreductor diseñado para accionar sistemas de alimentación por cadena, proporcionando una transmisión de potencia eficiente y un funcionamiento continuo para el transporte automático de alimento en granjas.',
                'materiales': 'Carcasa de alta resistencia.',
                'componentes': 'Motor monofásico de 2 HP. Velocidad: 1,800 RPM. Caja reductora con relación 20:1. Alto torque para un desempeño confiable. Bajo mantenimiento y larga vida útil. Compatible con sistemas automáticos de alimentación por cadena.',
            },
            {
                'categoria': 'MOTORES_REDUCTORES',
                'subcategoria': None,
                'nombre': 'Caja prereductora + motor para sinfín',
                'slug': 'caja-prereductora-motor-sinfin',
                'orden': 38,
                'descripcion_corta': 'Conjunto de caja prereductora y motor para sistemas de sinfín de 30 m y 60 m.',
                'descripcion': 'Conjunto de caja prereductora y motor diseñado para accionar sistemas de alimentación por sinfín, disponible para líneas de 30 m y 60 m de longitud. Proporciona una transmisión de potencia eficiente, un funcionamiento continuo y un transporte uniforme del alimento.',
                'componentes': 'Disponible para sistemas de sinfín de 30 m y 60 m. Caja prereductora de alto torque. Motor de alto rendimiento para trabajo continuo. Transmisión de potencia eficiente y confiable. Bajo mantenimiento y larga vida útil. Compatible con sistemas automáticos de alimentación.',
            },
            {
                'categoria': 'MOTORES_REDUCTORES',
                'subcategoria': None,
                'nombre': 'Caja reductora NMRV 130',
                'slug': 'caja-reductora-nmrv-130',
                'orden': 39,
                'descripcion_corta': 'Caja reductora NMRV 130 para agitadores de estiércol.',
                'descripcion': 'Caja reductora NMRV 130 diseñada para la transmisión de potencia en agitadores de estiércol, proporcionando un alto torque, un funcionamiento confiable y un desempeño continuo en aplicaciones de trabajo pesado.',
                'componentes': 'Modelo: NMRV 130. Relación de reducción: 40:1. Diámetro del eje: 35 mm. Alto torque para aplicaciones de carga continua. Carcasa de alta resistencia. Bajo mantenimiento y larga vida útil. Ideal para sistemas de agitadores de estiércol.',
            },
            {
                'categoria': 'MOTORES_REDUCTORES',
                'subcategoria': None,
                'nombre': 'Motor para agitador de estiércol',
                'slug': 'motor-agitador-estiercol',
                'orden': 40,
                'descripcion_corta': 'Motor monofásico de 3 HP para agitadores de estiércol.',
                'descripcion': 'Motor monofásico diseñado para accionar agitadores de estiércol, ofreciendo un funcionamiento confiable, eficiente y continuo en sistemas de manejo de purines para granjas porcícolas.',
                'materiales': 'Carcasa en aluminio de alta resistencia.',
                'componentes': 'Potencia: 3 HP. Motor monofásico. Velocidad: 1,750 RPM. Excelente desempeño para trabajo continuo. Bajo mantenimiento y larga vida útil. Ideal para sistemas de agitación de estiércol.',
            },

            # ===========================================
            # PRODUCCIÓN PORCINA - Bebederos (041-044)
            # ===========================================
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'bebederos',
                'nombre': 'Chupón lechón y adulto',
                'slug': 'chupon-lechon-adulto',
                'orden': 41,
                'descripcion_corta': 'Bebedero tipo chupete para lechón y cerdos adultos.',
                'descripcion': 'El bebedero tipo chupete para lechón está diseñado para proporcionar un suministro continuo de agua limpia. Fabricado en acero inoxidable de alta resistencia, ofrece un funcionamiento confiable, reduce el desperdicio de agua y contribuye al bienestar y desarrollo de los cerdos.',
                'materiales': 'Acero inoxidable de alta calidad.',
                'componentes': 'Diseño resistente a la corrosión y al desgaste. Accionamiento suave para facilitar el consumo de agua. Reduce el desperdicio de agua. Fácil instalación y mantenimiento. Larga vida útil.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'bebederos',
                'nombre': 'Bebedero en H con manguera para ceba o precebo',
                'slug': 'bebedero-h-manguera-ceba-precebo',
                'orden': 42,
                'descripcion_corta': 'Bebedero en H con dos chupetes para cerdos en precebo y ceba.',
                'descripcion': 'El bebedero en H con manguera está diseñado para proporcionar un suministro continuo y eficiente de agua a cerdos en las etapas de precebo y ceba. Su estructura en acero galvanizado y los dos bebederos tipo chupete permiten abastecer simultáneamente a varios animales, optimizando el consumo de agua y mejorando el bienestar dentro del corral.',
                'materiales': 'Estructura en acero galvanizado.',
                'componentes': 'Estructura tipo H de alta resistencia. Incluye dos bebederos tipo chupete. Manguera flexible para conexión al suministro de agua. Fácil instalación y mantenimiento. Resistente a la corrosión y al desgaste.',
                'beneficios': 'Suministro constante de agua limpia. Permite el acceso simultáneo de varios animales. Reduce el desperdicio de agua. Favorece el bienestar y el desempeño productivo. Disminuye los costos de mantenimiento gracias a su alta durabilidad.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'bebederos',
                'nombre': 'Bebedero automático paridera y precebo',
                'slug': 'bebedero-automatico-paridera-precebo',
                'orden': 43,
                'descripcion_corta': 'Bebedero automático con cazoleta para paridera y precebo.',
                'descripcion': 'El bebedero automático para paridera y precebo está diseñado para garantizar un suministro continuo de agua limpia a lechones durante sus primeras etapas de crecimiento. Su estructura en acero inoxidable ofrece alta resistencia a la corrosión y una larga vida útil, mientras que su sistema de fijación permite una instalación segura, anclado directamente a la pared o a la estructura de la paridera.',
                'materiales': 'Acero inoxidable de alta calidad.',
                'componentes': 'Incluye cazoleta con bebedero automático integrado. Diseño resistente para uso continuo en ambientes porcícolas. Instalación mediante anclaje a la pared o paridera. Reduce el desperdicio de agua. Fácil limpieza y mantenimiento. Alta resistencia a la corrosión y al desgaste.',
                'aplicaciones': 'Parideras. Corrales de precebo.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'bebederos',
                'nombre': 'Bebedero para ceba',
                'slug': 'bebedero-ceba',
                'orden': 44,
                'descripcion_corta': 'Bebedero de acero galvanizado con doble salida para ceba.',
                'descripcion': 'Proporciona agua limpia y constante para cerdos en etapa de ceba.',
                'materiales': 'Acero galvanizado de alta resistencia.',
                'componentes': 'Doble salida con chupetes. Fácil instalación. Bajo mantenimiento.',
            },

            # ===========================================
            # PRODUCCIÓN PORCINA - Jaulas de maternidad y gestación (045-046)
            # ===========================================
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'jaulas_maternidad_gestacion',
                'nombre': 'Jaula de maternidad',
                'slug': 'jaula-maternidad',
                'orden': 45,
                'descripcion_corta': 'Jaula de maternidad con piso para cerda y área de calefacción para lechones.',
                'descripcion': 'La jaula de maternidad está diseñada para brindar un ambiente seguro, cómodo y funcional durante el parto y la lactancia. Su estructura galvanizada de alta resistencia protege a la cerda y a los lechones, mientras que el sistema de pisos facilita la higiene y el manejo diario.',
                'materiales': 'Estructura en acero galvanizado de alta resistencia. Divisiones laterales en PVC. Piso plástico para lechones. Comedero en acero inoxidable.',
                'componentes': 'Piso para la cerda con abertura posterior que facilita la evacuación de las heces. Piso plástico para lechones, resistente y de fácil limpieza. Área de descanso para lechones con tapa y lámparas de calefacción. Incluye comedero y sistema de bebida para la cerda. Diseño que facilita el acceso para alimentación, limpieza y manejo.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'jaulas_maternidad_gestacion',
                'nombre': 'Jaula de gestación',
                'slug': 'jaula-gestacion',
                'orden': 46,
                'descripcion_corta': 'Jaula de gestación en acero galvanizado con comedero inoxidable.',
                'descripcion': 'La jaula de gestación está diseñada para brindar seguridad, confort y un manejo eficiente de las cerdas durante la etapa de gestación. Su estructura en acero galvanizado de alta resistencia proporciona una excelente durabilidad y estabilidad, permitiendo un alojamiento individual que facilita la alimentación, el monitoreo sanitario y el bienestar del animal.',
                'materiales': 'Acero galvanizado de alta resistencia.',
                'componentes': 'Puerta frontal y posterior con sistema de cierre seguro. Comedero en acero inoxidable de alta durabilidad. Patas con placas para anclaje al piso. Componentes desmontables para facilitar la instalación. Superficie resistente a la corrosión y al desgaste. Fácil limpieza y mantenimiento.',
            },

            # ===========================================
            # PRODUCCIÓN PORCINA - Plaquetas (047-049)
            # ===========================================
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'plaquetas_lechon_madre',
                'nombre': 'Slat para madres adultas - 60 × 40 cm',
                'slug': 'slat-madres-adultas-60x40',
                'orden': 47,
                'descripcion_corta': 'Slat plástico de 60 × 40 cm para madres adultas en gestación y maternidad.',
                'descripcion': 'El slat plástico para madres adultas de 60 × 40 cm está diseñado para proporcionar un piso seguro, higiénico y de alta resistencia en áreas de gestación y maternidad. Fabricado en polipropileno de alta calidad, soporta el peso de las cerdas adultas, facilita el drenaje de líquidos y contribuye a mantener un ambiente limpio y seco dentro de la granja.',
                'materiales': 'Polipropileno (PP) de alta resistencia.',
                'dimensiones': '60 × 40 cm.',
                'componentes': 'Diseño antideslizante para mayor seguridad. Ranuras que facilitan el drenaje de líquidos y desechos. Alta capacidad de carga para cerdas adultas. Sistema de ensamblaje modular de fácil instalación. Resistente a la humedad, productos químicos y corrosión. Superficie de fácil limpieza y desinfección.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'plaquetas_lechon_madre',
                'nombre': 'Slat para precebo y lechoneras - 60 × 60 cm',
                'slug': 'slat-precebo-lechoneras-60x60',
                'orden': 48,
                'descripcion_corta': 'Slat plástico de 60 × 60 cm para precebo y lechoneras.',
                'descripcion': 'El slat plástico de 60 × 60 cm está diseñado para brindar un piso seguro, higiénico y confortable en corrales de precebo y lechoneras en parideras. Fabricado en polipropileno (PP) de alta resistencia, proporciona una excelente capacidad de drenaje, manteniendo un ambiente limpio y seco que favorece el bienestar y el desarrollo de los lechones.',
                'materiales': 'Polipropileno (PP) de alta resistencia.',
                'dimensiones': '60 × 60 cm.',
                'componentes': 'Disponible en color naranja y verde. Diseño antideslizante para mayor seguridad. Ranuras que facilitan el drenaje de líquidos y desechos. Sistema de ensamblaje modular de fácil instalación. Alta resistencia al desgaste, humedad y productos de limpieza. Superficie de fácil lavado y desinfección.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'plaquetas_lechon_madre',
                'nombre': 'Slat para precebo y lechoneras - 60 × 70 cm',
                'slug': 'slat-precebo-lechoneras-60x70',
                'orden': 49,
                'descripcion_corta': 'Slat plástico de 60 × 70 cm para precebo y lechoneras.',
                'descripcion': 'El slat plástico de 60 × 70 cm está diseñado para ofrecer un piso resistente, higiénico y confortable en corrales de precebo y lechoneras en parideras. Fabricado en polipropileno (PP) de alta resistencia, proporciona una excelente capacidad de drenaje que mantiene las instalaciones limpias y secas, favoreciendo el bienestar y el desarrollo de los lechones.',
                'materiales': 'Polipropileno (PP) de alta resistencia.',
                'dimensiones': '60 × 70 cm.',
                'componentes': 'Superficie antideslizante para mayor seguridad. Ranuras diseñadas para un eficiente drenaje de líquidos y desechos. Sistema de ensamblaje modular de fácil instalación. Alta resistencia a la humedad, productos químicos y corrosión. Fácil limpieza y desinfección.',
            },

            # ===========================================
            # PRODUCCIÓN PORCINA - Slats fibra de vidrio (050-051)
            # ===========================================
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'slats_fibra_vidrio',
                'nombre': 'Slat BMC maternidad o paridera',
                'slug': 'slat-bmc-maternidad-paridera',
                'orden': 50,
                'descripcion_corta': 'Piso BMC en fibra de vidrio para maternidad y paridera.',
                'descripcion': 'El piso BMC para maternidad y paridera está fabricado en BMC (Bulk Molding Compound), un material compuesto de alto rendimiento reforzado con fibra de vidrio, diseñado para soportar las exigentes condiciones de las granjas porcinas. Esta tecnología ofrece una excelente resistencia mecánica, alta capacidad de carga y una larga vida útil, incluso en ambientes de alta humedad y exposición constante a productos de limpieza.',
                'materiales': 'BMC (Bulk Molding Compound), material compuesto reforzado con fibra de vidrio.',
                'dimensiones': '60 cm de ancho × 2.40 m de largo. Altura: 6 cm.',
                'componentes': 'Alta capacidad de carga para soportar cerdas adultas. Excelente resistencia al impacto, desgaste y deformación. Superficie antideslizante. Diseño con ranuras para drenaje. Resistente a la humedad, corrosión y agentes químicos. Fácil limpieza y desinfección. Larga vida útil con mínimo mantenimiento.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'slats_fibra_vidrio',
                'nombre': 'Slat BMC para cárcamo, gestación y corrales de ceba',
                'slug': 'slat-bmc-carcamo-gestacion-ceba',
                'orden': 51,
                'descripcion_corta': 'Piso BMC en fibra de vidrio para cárcamo, gestación y ceba.',
                'descripcion': 'El piso BMC para cárcamo en gestación y corrales de ceba está fabricado en BMC (Bulk Molding Compound), un material compuesto reforzado con fibra de vidrio, diseñado para soportar las exigencias de las explotaciones porcinas. Gracias a su alta resistencia mecánica y capacidad de carga, es ideal para áreas donde se alojan cerdas gestantes y cerdos de ceba.',
                'materiales': 'BMC (Bulk Molding Compound), material compuesto reforzado con fibra de vidrio.',
                'dimensiones': '60 cm de ancho × 2.40 m de largo. Altura: 6 cm.',
                'componentes': 'Alta resistencia para soportar el peso de cerdas gestantes y cerdos de ceba. Excelente resistencia al impacto, desgaste y deformación. Diseño con ranuras para drenaje. Superficie antideslizante. Resistente a la humedad, corrosión y productos químicos. Fácil limpieza y desinfección. Larga vida útil con mínimo mantenimiento.',
            },

            # ===========================================
            # PRODUCCIÓN PORCINA - Corrales, paneles PVC (052-053)
            # ===========================================
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'corrales_paneles_puertas',
                'nombre': 'Panel divisorio en PVC',
                'slug': 'panel-divisorio-pvc',
                'orden': 52,
                'descripcion_corta': 'Panel divisorio en PVC multicámara para separación de corrales.',
                'descripcion': 'Panel divisorio fabricado en PVC de alta resistencia con estructura multicámara reforzada, diseñado para la separación de corrales en granjas porcinas. Su construcción ofrece excelente rigidez, alta durabilidad y resistencia a la humedad, facilitando la limpieza y garantizando una mayor vida útil.',
                'materiales': 'PVC de alta resistencia.',
                'componentes': 'Panel de 50 cm de altura para parideras. Panel de 70 cm de altura para corrales de precebo. Colores disponibles: blanco y gris. Estructura: perfil multicámara reforzado. Superficie: lisa, no porosa y de fácil limpieza. Alta resistencia a la humedad, corrosión y productos de desinfección. Compatible con perfiles y accesorios de instalación.',
                'aplicaciones': 'Parideras. Corrales de precebo. Divisiones internas para instalaciones porcinas.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'corrales_paneles_puertas',
                'nombre': 'Pletina T12 en fibra de vidrio',
                'slug': 'pletina-t12-fibra-vidrio',
                'orden': 53,
                'descripcion_corta': 'Pletina estructural T12 en fibra de vidrio para soporte de pisos slat.',
                'descripcion': 'La pletina T12 en fibra de vidrio es un perfil estructural diseñado para servir como soporte de pisos tipo slat en instalaciones porcinas. Fabricada en material compuesto de alta resistencia, ofrece excelente capacidad de carga, resistencia a la corrosión y una larga vida útil, incluso en ambientes de alta humedad y exposición a agentes químicos.',
                'materiales': 'Fibra de vidrio reforzada (PRFV).',
                'componentes': 'Tipo: pletina estructural T12 para soporte de slat. Presentaciones: 6.00 m, 3.00 m, 2.40 m, 1.80 m, 0.60 m. Alta resistencia a la humedad y la corrosión. No se oxida ni requiere mantenimiento. Compatible con sistemas de pisos plásticos y de fibra de vidrio. Excelente estabilidad estructural y larga vida útil.',
                'aplicaciones': 'Soporte para pisos tipo slat. Parideras. Precebos. Gestación. Corrales de ceba. Sistemas de drenaje y cárcamos.',
            },

            # ===========================================
            # PRODUCCIÓN PORCINA - Corrales, divisiones y puertas (054-056)
            # ===========================================
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'corrales_divisiones_puertas',
                'nombre': 'Herrajes galvanizados para panel',
                'slug': 'herrajes-galvanizados-panel',
                'orden': 54,
                'descripcion_corta': 'Herrajes en acero galvanizado para instalación de puertas, paneles y divisiones.',
                'descripcion': 'Línea de herrajes fabricados en acero galvanizado de alta resistencia, diseñados para la instalación, unión y funcionamiento de puertas, paneles y divisiones en corrales de precebo. Su acabado galvanizado proporciona una excelente protección contra la corrosión, garantizando una larga vida útil incluso en ambientes de alta humedad.',
                'materiales': 'Acero galvanizado.',
                'componentes': 'Altura: 70 cm y 50 cm. Alta resistencia mecánica al uso continuo. Protección contra la corrosión y oxidación. Diseño para fácil instalación y mantenimiento. Compatibles con diferentes sistemas de corrales metálicos. Disponibles en medidas de 50 cm y de 70 cm de altura.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'corrales_divisiones_puertas',
                'nombre': 'Reja metálica galvanizada',
                'slug': 'reja-metalica-galvanizada',
                'orden': 55,
                'descripcion_corta': 'Reja metálica galvanizada para división de corrales de ceba.',
                'descripcion': 'La reja metálica galvanizada para división de corrales de ceba está diseñada para la separación segura y eficiente de animales en instalaciones porcinas. Fabricada en acero galvanizado de alta resistencia, ofrece una estructura robusta, excelente durabilidad y resistencia a la corrosión, ideal para ambientes de alta humedad y uso continuo.',
                'materiales': 'Acero galvanizado de alta resistencia.',
                'componentes': 'Medida estándar: 1.78 m de largo. Fabricación: disponible en medidas especiales según los requerimientos del cliente. Estructura: tubería galvanizada con refuerzos estructurales. Instalación: compatible con postes y sistemas de fijación para corrales porcinos.',
                'aplicaciones': 'Corrales de ceba. División de áreas en granjas porcinas. Corrales de manejo y alojamiento. Proyectos nuevos o remodelación de instalaciones.',
            },
            {
                'categoria': 'PRODUCCION_PORCINA',
                'subcategoria': 'corrales_divisiones_puertas',
                'nombre': 'Puerta metálica galvanizada para corral de ceba',
                'slug': 'puerta-metalica-galvanizada-ceba',
                'orden': 56,
                'descripcion_corta': 'Puerta galvanizada para corral de ceba con barras horizontales.',
                'descripcion': 'La puerta metálica galvanizada para corral de ceba está diseñada para brindar un acceso seguro, resistente y de fácil manejo en corrales porcinos. Fabricada en acero galvanizado de alta calidad, ofrece excelente resistencia a la corrosión y una larga vida útil, incluso en ambientes de alta humedad y exposición constante.',
                'materiales': 'Acero galvanizado por inmersión en caliente.',
                'dimensiones': 'Altura: 96 cm. Ancho: 126 cm.',
                'componentes': 'Diseño: barras horizontales que proporcionan alta resistencia estructural y facilitan la inspección de los animales. Fabricación: disponible en medidas estándar y también bajo especificaciones del cliente. Alta resistencia a la humedad, corrosión y ambientes agresivos. Estructura robusta para uso continuo. Fácil apertura y cierre. Diseño que facilita el manejo y movimiento de los animales. Bajo mantenimiento y larga vida útil. Ideal para integrar con sistemas de divisiones metálicas galvanizadas.',
            },

            # ===========================================
            # REPUESTOS Y ACCESORIOS - Para comedero y dosificador (057-058)
            # ===========================================
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'comedero_dosificador',
                'nombre': 'Repuestos para dosificador',
                'slug': 'repuestos-dosificador',
                'orden': 57,
                'descripcion_corta': 'Repuestos para dosificador: regla, cierre y tapa dosificadora.',
                'descripcion': 'Repuestos fabricados en plástico de alta resistencia para el mantenimiento y correcto funcionamiento del dosificador de alimento. Incluye regla dosificadora, cierre dosificador y tapa dosificador, garantizando una regulación precisa, un cierre seguro y la protección del sistema de alimentación.',
                'materiales': 'Plástico de alta resistencia.',
                'componentes': 'Regla dosificadora, cierre dosificador y tapa dosificador. Resistentes al desgaste y la humedad. Fácil instalación y reemplazo. Compatibles con dosificadores de alimento. Prolongan la vida útil del equipo y optimizan la dosificación del alimento.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'comedero_dosificador',
                'nombre': 'Tapa para comedero tolva 140 L',
                'slug': 'tapa-comedero-tolva-140l',
                'orden': 58,
                'descripcion_corta': 'Tapa de repuesto para comedero tolva de 140 litros.',
                'descripcion': 'Tapa de repuesto fabricada en plástico de alta resistencia para comedero tolva de 140 litros. Diseñada para proteger el alimento de la humedad, el polvo y otros contaminantes, contribuyendo a conservar su calidad y reduciendo el desperdicio.',
                'materiales': 'Plástico de alta resistencia.',
                'componentes': 'Compatible con comedero tolva de 140 L. Protege el alimento de la humedad y la suciedad. Fácil instalación y reemplazo. Resistente a la intemperie y al uso continuo en granjas.',
            },

            # ===========================================
            # REPUESTOS Y ACCESORIOS - Para automatización (059-066)
            # ===========================================
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'automatizacion_repuestos',
                'nombre': 'Bocas descarga',
                'slug': 'bocas-descarga-repuestos',
                'orden': 59,
                'descripcion_corta': 'Bocas de descarga para tubería de 60 mm y 75 mm.',
                'descripcion': 'Bocas de descarga fabricadas en plástico de alta resistencia, diseñadas para garantizar una descarga eficiente del alimento y una conexión segura con el sistema de transporte.',
                'materiales': 'Plástico de alta resistencia.',
                'componentes': 'Disponibles para tubería de 60 mm y 75 mm. Alta resistencia al desgaste y a la corrosión. Fácil instalación y reemplazo. Compatibles con sistemas de alimentación automática para granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'automatizacion_repuestos',
                'nombre': 'Acople en Y',
                'slug': 'acople-en-y',
                'orden': 60,
                'descripcion_corta': 'Acople en Y para doble bajante en sistemas de alimentación.',
                'descripcion': 'Acople en "Y" fabricado en plástico de alta resistencia, diseñado para distribuir el alimento desde una línea de transporte hacia dos bajantes, garantizando un flujo uniforme y una alimentación eficiente en sistemas automáticos.',
                'materiales': 'Plástico de alta resistencia.',
                'componentes': 'Diseño en "Y" para doble bajante. Distribución uniforme del alimento. Fácil instalación y reemplazo. Compatible con sistemas automáticos de alimentación porcina. Resistente al desgaste, la humedad y ambientes de granja.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'automatizacion_repuestos',
                'nombre': 'Cajetín de 60 mm',
                'slug': 'cajetin-60mm-repuesto',
                'orden': 61,
                'descripcion_corta': 'Cajetín en acero inoxidable para línea de transporte de 60 mm.',
                'descripcion': 'Cajetín fabricado en acero inoxidable, diseñado para recibir y conducir el alimento hacia una línea de transporte de 60 mm, garantizando un flujo eficiente y una excelente resistencia para uso continuo.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Diámetro de salida: 60 mm. Configuración: salida sencilla. Alta resistencia a la corrosión y al desgaste. Fácil limpieza y mantenimiento.',
                'aplicaciones': 'Sistemas de alimentación automatizada para granjas porcinas y ganaderas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'automatizacion_repuestos',
                'nombre': 'Eslabón para empate de cadena',
                'slug': 'eslabon-empate-cadena',
                'orden': 62,
                'descripcion_corta': 'Eslabón de repuesto para unir o empatar la cadena de transporte.',
                'descripcion': 'Eslabón de repuesto fabricado en acero galvanizado de alta resistencia, diseñado para unir o empatar la cadena de transporte de alimento en sistemas automáticos de alimentación. Garantiza una conexión segura, resistente y un funcionamiento continuo del sistema.',
                'materiales': 'Acero galvanizado de alta resistencia.',
                'componentes': 'Diseñado para el empate o unión de la cadena. Alta resistencia al desgaste y la corrosión. Fácil instalación y reemplazo. Compatible con sistemas automáticos de transporte de alimento para granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'automatizacion_repuestos',
                'nombre': 'Corner para sistema de alimentación',
                'slug': 'corner-sistema-alimentacion',
                'orden': 63,
                'descripcion_corta': 'Corner de repuesto en acero inoxidable o plástico azul.',
                'descripcion': 'Corner de repuesto disponible en acero inoxidable y plástico de alta resistencia (azul), diseñado para guiar el recorrido de la cadena en los cambios de dirección del sistema automático de alimentación.',
                'materiales': 'Acero inoxidable y plástico de alta resistencia.',
                'componentes': 'Guía la cadena en cambios de dirección. Reduce el desgaste del sistema de transporte. Alta resistencia a la corrosión y al uso continuo. Fácil instalación y reemplazo.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'automatizacion_repuestos',
                'nombre': 'Bajante para sistema de alimentación',
                'slug': 'bajante-sistema-alimentacion-repuesto',
                'orden': 64,
                'descripcion_corta': 'Bajante en acero galvanizado para conducir alimento a puntos de descarga.',
                'descripcion': 'Bajante fabricado en acero galvanizado, diseñado para conducir el alimento desde la línea de transporte hasta los puntos de descarga de forma eficiente y segura.',
                'materiales': 'Acero galvanizado.',
                'componentes': 'Alta resistencia a la corrosión y al desgaste. Diseño con ángulo de descarga para un flujo uniforme del alimento. Fácil instalación en sistemas de alimentación automatizada. Fabricado para una larga vida útil.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'automatizacion_repuestos',
                'nombre': 'Cajetín de 75 mm con rasera',
                'slug': 'cajetin-75mm-rasera-repuesto',
                'orden': 65,
                'descripcion_corta': 'Cajetín en acero inoxidable con rasera para línea de 75 mm.',
                'descripcion': 'Cajetín fabricado en acero inoxidable, equipado con rasera de cierre para controlar el paso del alimento hacia la línea de transporte de 75 mm, permitiendo una operación segura y un mantenimiento sencillo.',
                'materiales': 'Acero inoxidable.',
                'componentes': 'Diámetro de salida: 75 mm. Incluye: rasera de cierre manual. Alta resistencia a la corrosión y al desgaste. Fácil limpieza y mantenimiento.',
                'aplicaciones': 'Sistemas de alimentación automatizada para granjas porcinas y ganaderas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'automatizacion_repuestos',
                'nombre': 'Eje giratorio para sinfín',
                'slug': 'eje-giratorio-sinfin',
                'orden': 66,
                'descripcion_corta': 'Eje giratorio para transmitir movimiento al sistema de sinfín.',
                'descripcion': 'Eje giratorio fabricado en materiales de alta resistencia, diseñado para transmitir el movimiento al sistema de sinfín, garantizando un funcionamiento estable, eficiente y continuo en los sistemas automáticos de transporte de alimento.',
                'materiales': 'Materiales de alta resistencia.',
                'componentes': 'Proporciona una transmisión de movimiento eficiente. Alta resistencia al desgaste y al uso continuo. Fácil instalación y reemplazo. Compatible con sistemas de alimentación automática por sinfín para granjas.',
            },

            # ===========================================
            # REPUESTOS Y ACCESORIOS - Tornillería y accesorios (067-078)
            # ===========================================
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Tornillería para instalación',
                'slug': 'tornilleria-instalacion',
                'orden': 67,
                'descripcion_corta': 'Tornillería y accesorios de fijación para instalación de equipos porcícolas.',
                'descripcion': 'Línea de tornillería y accesorios de fijación para la instalación de equipos, estructuras y sistemas de alimentación porcícola. Fabricados con materiales de alta resistencia para garantizar una instalación segura, firme y duradera.',
                'materiales': 'Acero de alta resistencia.',
                'componentes': 'Disponibles en diferentes medidas y referencias. Incluye grilletes, tornillos autoperforantes, cáncamos y chazos de expansión. Fácil instalación. Alta resistencia a la corrosión y al uso continuo. Ideales para el montaje de equipos y estructuras en granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Guaya acerada 3/16',
                'slug': 'guaya-acerada-3-16',
                'orden': 68,
                'descripcion_corta': 'Guaya acerada de 3/16" para suspensión y fijación.',
                'descripcion': 'Guaya acerada de 3/16", fabricada en acero de alta resistencia para aplicaciones de suspensión, soporte y fijación en sistemas porcícolas. Ofrece excelente capacidad de carga, durabilidad y resistencia al desgaste en ambientes de trabajo exigentes.',
                'materiales': 'Acero de alta resistencia.',
                'componentes': 'Diámetro: 3/16". Excelente resistencia a la tracción. Alta durabilidad y resistencia a la corrosión. Flexible y de fácil instalación. Ideal para sistemas de suspensión, izaje y soporte de equipos en granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Resorte galvanizado',
                'slug': 'resorte-galvanizado',
                'orden': 69,
                'descripcion_corta': 'Resorte galvanizado de 20 cm para sistemas de suspensión.',
                'descripcion': 'Resorte galvanizado de 20 cm, diseñado para proporcionar tensión y absorción de movimiento en sistemas de suspensión y montaje de equipos porcícolas. Su acabado galvanizado ofrece mayor resistencia a la corrosión y una larga vida útil.',
                'materiales': 'Acero galvanizado.',
                'componentes': 'Longitud: 20 cm. Alta resistencia a la tensión y al desgaste. Excelente resistencia a la corrosión. Fácil instalación. Ideal para sistemas de suspensión y soporte en granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Poleas metálicas',
                'slug': 'poleas-metalicas',
                'orden': 70,
                'descripcion_corta': 'Poleas metálicas para desplazamiento de guayas y cables de acero.',
                'descripcion': 'Poleas metálicas diseñadas para el desplazamiento seguro y eficiente de guayas y cables de acero en sistemas de suspensión y elevación. Fabricadas con materiales de alta resistencia para ofrecer un funcionamiento confiable y una larga vida útil.',
                'materiales': 'Acero galvanizado de alta resistencia.',
                'componentes': 'Disponibles en 3" y 7/8". Giro suave que reduce el desgaste de la guaya. Alta resistencia a la corrosión. Fácil instalación. Ideales para sistemas de suspensión, elevación y soporte de equipos en granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Malacates manuales',
                'slug': 'malacates-manuales',
                'orden': 71,
                'descripcion_corta': 'Malacates manuales de 1,600 lb y 2,000 lb para izaje y elevación.',
                'descripcion': 'Malacates manuales diseñados para el izaje, tensionado y desplazamiento de cargas en sistemas de suspensión y manejo de equipos. Fabricados con materiales de alta resistencia para garantizar un funcionamiento seguro, confiable y duradero.',
                'materiales': 'Acero de alta resistencia.',
                'componentes': 'Disponibles en capacidades de 1,600 lb y 2,000 lb. Sistema de engranajes para un accionamiento suave y eficiente. Guaya de acero de alta resistencia. Fácil instalación y operación. Ideales para sistemas de elevación y suspensión en granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Base para malacate',
                'slug': 'base-malacate',
                'orden': 72,
                'descripcion_corta': 'Base metálica para instalación y fijación de malacates.',
                'descripcion': 'Base metálica diseñada para la instalación y fijación segura de malacates en sistemas de suspensión y elevación. Fabricada en acero de alta resistencia para proporcionar estabilidad, seguridad y una larga vida útil en aplicaciones porcícolas.',
                'materiales': 'Acero de alta resistencia.',
                'componentes': 'Diseño reforzado para mayor estabilidad. Múltiples perforaciones para una instalación segura. Acabado resistente a la corrosión. Fácil montaje y mantenimiento. Compatible con malacates de diferentes capacidades.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Rollo de piola',
                'slug': 'rollo-piola',
                'orden': 73,
                'descripcion_corta': 'Rollo de piola de alta resistencia para amarre y suspensión.',
                'descripcion': 'Rollo de piola de alta resistencia, diseñado para aplicaciones de amarre, suspensión y sujeción en sistemas de producción porcícola. Su alta durabilidad y flexibilidad garantizan un desempeño confiable en diferentes aplicaciones.',
                'materiales': 'Material de alta resistencia.',
                'componentes': 'Excelente resistencia a la tensión y al desgaste. Flexible y de fácil manipulación. Resistente a la humedad y al uso continuo. Disponible en presentación por rollo. Ideal para labores de amarre, suspensión y fijación en granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Cortina laminada importada',
                'slug': 'cortina-laminada-importada',
                'orden': 74,
                'descripcion_corta': 'Cortina laminada importada en azul y amarillo para control ambiental.',
                'descripcion': 'Cortina laminada importada de alta resistencia, disponible en color azul y amarillo, diseñada para el control ambiental en galpones porcícolas. Brinda protección contra el viento, la lluvia y las variaciones de temperatura, contribuyendo al bienestar de los animales.',
                'materiales': 'Lona laminada de alta resistencia.',
                'componentes': 'Disponible en color azul y amarillo. Resistente a la humedad, rayos UV y desgarros. Flexible y de fácil instalación. Larga vida útil en ambientes de trabajo exigentes. Ideal para sistemas de cortinas en granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Malla hexagonal plastificada',
                'slug': 'malla-hexagonal-plastificada',
                'orden': 75,
                'descripcion_corta': 'Malla hexagonal plastificada para cerramiento de instalaciones agropecuarias.',
                'descripcion': 'Malla hexagonal plastificada de alta resistencia, ideal para el cerramiento y protección de instalaciones agropecuarias. Disponible en diferentes medidas según la necesidad del proyecto, ofreciendo durabilidad y excelente resistencia a la intemperie.',
                'materiales': 'Alambre galvanizado con recubrimiento plastificado.',
                'componentes': 'Disponible en diferentes medidas según requerimiento. Alta resistencia a la corrosión y a los rayos UV. Flexible y de fácil instalación. Larga vida útil en ambientes exteriores. Ideal para cerramientos, divisiones y protección de granjas porcícolas y avícolas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Arrancador eléctrico',
                'slug': 'arrancador-electrico',
                'orden': 76,
                'descripcion_corta': 'Arrancador eléctrico para protección y accionamiento de motores.',
                'descripcion': 'Arrancador eléctrico diseñado para el accionamiento y protección de motores utilizados en sistemas de alimentación, ventilación y automatización en granjas porcícolas. Garantiza un arranque seguro, confiable y un funcionamiento eficiente del equipo.',
                'componentes': 'Protección contra sobrecargas eléctricas. Arranque seguro y confiable del motor. Componentes de alta calidad y larga vida útil. Fácil instalación y mantenimiento. Compatible con diferentes potencias de motores. Ideal para sistemas automáticos y equipos porcícolas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Tubo galvanizado con rosca para cortina',
                'slug': 'tubo-galvanizado-rosca-cortina',
                'orden': 77,
                'descripcion_corta': 'Tubo galvanizado con rosca para instalación de sistemas de cortinas.',
                'descripcion': 'Tubo galvanizado con rosca, diseñado para la instalación y accionamiento de sistemas de cortinas en galpones porcícolas. Su fabricación en acero galvanizado proporciona alta resistencia mecánica y excelente protección contra la corrosión.',
                'materiales': 'Acero galvanizado de alta resistencia.',
                'componentes': 'Extremos con rosca para una instalación segura. Excelente resistencia a la corrosión y la humedad. Alta durabilidad para trabajo continuo. Fácil instalación y mantenimiento. Ideal para sistemas de cortinas en granjas.',
            },
            {
                'categoria': 'REPUESTOS_ACCESORIOS',
                'subcategoria': 'tornilleria_accesorios',
                'nombre': 'Tuberías para sistemas de alimentación',
                'slug': 'tuberias-sistemas-alimentacion',
                'orden': 78,
                'descripcion_corta': 'Tuberías en acero galvanizado y PVC para transporte de alimento.',
                'descripcion': 'Tuberías diseñadas para el transporte eficiente de alimento en sistemas automáticos de alimentación porcícola. Disponibles en acero galvanizado para sistemas de sinfín y en PVC de alta resistencia para sistemas de cadena, garantizando durabilidad, resistencia al desgaste y un funcionamiento confiable.',
                'materiales': 'Acero galvanizado y PVC de alta resistencia.',
                'componentes': 'Longitud estándar: 6 m. Alta resistencia al desgaste y la corrosión. Compatibles con sistemas automáticos de transporte de alimento.',
                'aplicaciones': 'Tubo galvanizado: para sistemas de alimentación por sinfín (espiral). Tubería PVC: para sistemas de alimentación por cadena.',
            },

            # ===========================================
            # EQUIPOS COMPLEMENTARIOS (079-087)
            # ===========================================
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Criadora para lechones',
                'slug': 'criadora-lechones',
                'orden': 79,
                'descripcion_corta': 'Criadora para proporcionar ambiente cálido a lechones en maternidad.',
                'descripcion': 'La criadora para lechones proporciona un ambiente cálido, seguro y confortable durante las primeras etapas de vida, ayudando a mantener una temperatura adecuada que favorece el bienestar, reduce el estrés por frío y mejora el desarrollo de los animales.',
                'beneficios': 'Mantiene una temperatura óptima para los lechones. Favorece el bienestar y el confort animal. Reduce el estrés causado por bajas temperaturas. Contribuye a disminuir la mortalidad neonatal. Promueve un crecimiento más uniforme de los lechones. Fabricada con materiales resistentes, higiénicos y de fácil limpieza. Diseño que facilita la instalación y el mantenimiento. Ideal para salas de maternidad en granjas porcinas.',
            },
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Panel arreador',
                'slug': 'panel-arreador',
                'orden': 80,
                'descripcion_corta': 'Panel en plástico de alta resistencia para manejo y desplazamiento de cerdos.',
                'descripcion': 'El panel arreador está diseñado para facilitar el manejo y desplazamiento seguro de los cerdos durante las labores de producción. Fabricado en plástico de alta resistencia, ofrece una excelente durabilidad, es liviano, fácil de manipular y resistente a la humedad y a los productos de limpieza, convirtiéndose en una herramienta indispensable para el manejo diario en la granja.',
                'dimensiones': '121 × 76 × 3 cm.',
                'materiales': 'Plástico de alta resistencia.',
                'beneficios': 'Facilita el manejo y desplazamiento de los animales. Reduce el estrés durante el traslado de los cerdos. Liviano y de fácil manipulación. Resistente a la humedad, la corrosión y los impactos. Superficie de fácil limpieza y desinfección. Diseño ergonómico con múltiples puntos de agarre. Ideal para labores de clasificación, traslado y manejo dentro de la granja.',
            },
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Carrillo de mortalidad',
                'slug': 'carrillo-mortalidad',
                'orden': 81,
                'descripcion_corta': 'Carrillo con malacate manual y llantas antipinchazos para retiro de mortalidad.',
                'descripcion': 'El carrillo de mortalidad está diseñado para facilitar el retiro seguro e higiénico de animales dentro de la granja. Fabricado en tubo galvanizado de alta resistencia, incorpora un malacate manual con guaya de 400 kg y llantas macizas antipinchazos, permitiendo una operación eficiente, segura y con un menor esfuerzo físico para el operario.',
                'capacidad': '400 kg.',
                'materiales': 'Tubo galvanizado de alta resistencia.',
                'componentes': 'Malacate manual con guaya de 400 kg. Llantas macizas antipinchazos.',
                'beneficios': 'Capacidad de carga de hasta 400 kg. Sistema de elevación con malacate manual. Llantas macizas antipinchazos. Resistente a la corrosión. Fácil de lavar y desinfectar. Reduce el esfuerzo físico del operario. Minimiza el contacto directo con la mortalidad. Contribuye al cumplimiento de las buenas prácticas porcinas.',
                'aplicaciones': 'Granjas porcinas. Manejo y retiro de mortalidad. Áreas de maternidad, destete, levante y ceba.',
            },
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Prueba de detección temprana de preñez',
                'slug': 'prueba-deteccion-preñez',
                'orden': 82,
                'descripcion_corta': 'Prueba rápida de detección temprana de preñez para vacas y cerdas.',
                'descripcion': 'La prueba de detección temprana de preñez permite confirmar de forma rápida, segura y confiable el estado reproductivo de vacas y cerdas mediante la detección de cambios en los niveles de progesterona. Su fácil uso y resultados en pocos minutos la convierten en una herramienta ideal para optimizar la gestión reproductiva en explotaciones ganaderas y porcinas.',
                'beneficios': 'Alta precisión diagnóstica. Resultados en aproximadamente 5 minutos. Fácil de utilizar. Detección temprana de preñez. Para vacas: permite identificar oportunamente animales vacíos. Para cerdas: facilita el seguimiento de cerdas inseminadas.',
            },
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Tejas termoacústicas',
                'slug': 'tejas-termoacusticas',
                'orden': 83,
                'descripcion_corta': 'Tejas termoacústicas para aislamiento térmico y acústico en granjas.',
                'descripcion': 'Las tejas termoacústicas están diseñadas para ofrecer aislamiento térmico y acústico, proporcionando mayor confort y protección en granjas porcinas, avícolas e instalaciones agroindustriales. Su estructura de alta resistencia ayuda a reducir la transmisión de calor y ruido, mejorando las condiciones internas de las instalaciones y aumentando la durabilidad de la cubierta.',
                'beneficios': 'Excelente aislamiento térmico y acústico. Reduce la temperatura al interior. Disminuye el ruido generado por lluvia y granizo. Alta resistencia a la humedad y la corrosión. Material liviano y de fácil instalación. Bajo mantenimiento y larga vida útil. Disponibles en perfil de cresta alta y cresta baja.',
                'especificaciones': 'Cresta baja: ancho 1.13 m, largo hasta 11.80 m y espesor 2 mm. Cresta alta: ancho 1.075 m, largo hasta 11.80 m y espesor 2.5 mm.',
                'aplicaciones': 'Granjas porcinas. Granjas avícolas. Lecherías. Bodegas. Plantas agroindustriales. Cubiertas industriales y comerciales.',
            },
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Lámpara de calefacción para parideras',
                'slug': 'lampara-calefaccion-parideras',
                'orden': 84,
                'descripcion_corta': 'Lámpara de calefacción con reflector de aluminio para parideras.',
                'descripcion': 'La lámpara de calefacción para parideras está diseñada para proporcionar una fuente de calor uniforme y segura durante los primeros días de vida de los lechones. Su reflector de aluminio concentra el calor de manera eficiente, creando un ambiente confortable que favorece el bienestar, reduce el estrés por frío y mejora la supervivencia y el desarrollo de los animales.',
                'beneficios': 'Proporciona calor uniforme para los lechones recién nacidos. Favorece el bienestar y el confort animal. Ayuda a reducir la mortalidad neonatal por bajas temperaturas. Reflector de aluminio de alta eficiencia térmica. Rejilla de protección para mayor seguridad. Fácil instalación y operación. Fabricada con materiales resistentes para una larga vida útil. Ideal para salas de maternidad y parideras.',
            },
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Lámpara de calefacción para precebo',
                'slug': 'lampara-calefaccion-precebo',
                'orden': 85,
                'descripcion_corta': 'Lámpara de calefacción con reflector de aluminio para precebo.',
                'descripcion': 'La lámpara de calefacción para precebo está diseñada para proporcionar una fuente de calor uniforme y constante, ayudando a mantener una temperatura adecuada durante la etapa de precebo. Su reflector de aluminio de alta eficiencia concentra el calor de manera óptima, favoreciendo el bienestar de los lechones, reduciendo el estrés por frío y promoviendo un mejor crecimiento y desarrollo.',
                'materiales': 'Reflector de aluminio. Rejilla de protección metálica. Portalámpara de alta resistencia. Cable de alimentación con enchufe.',
                'beneficios': 'Proporciona calor uniforme y eficiente. Favorece el confort y bienestar de los lechones. Ayuda a reducir el estrés ocasionado por bajas temperaturas. Reflector de aluminio de alta eficiencia térmica. Rejilla de protección para mayor seguridad. Fácil instalación y operación. Materiales resistentes y de larga vida útil. Bajo consumo de energía y excelente rendimiento.',
                'componentes': 'Compatible con bombillos infrarrojos para calefacción.',
            },
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Bombilla infrarroja para paridera',
                'slug': 'bombilla-infrarroja-paridera',
                'orden': 86,
                'descripcion_corta': 'Bombilla infrarroja de 175 W para calefacción de parideras.',
                'descripcion': 'Bombilla infrarroja diseñada para proporcionar una fuente de calor constante en parideras porcinas, ayudando a mantener la temperatura ideal para los lechones durante sus primeros días de vida y reduciendo el riesgo de hipotermia.',
                'especificaciones': 'Voltaje: 110 V. Potencia: 175 W. Tipo: bombilla infrarroja de calor. Rosca: E27 estándar. Material: vidrio templado con reflector. Color de luz: infrarrojo (calor).',
                'aplicaciones': 'Calefacción de nidos y parideras porcinas. Ideal para mantener el confort térmico de los lechones recién nacidos. Compatible con campanas o protectores para lámparas de calor.',
                'beneficios': 'Proporciona calor uniforme y constante. Favorece la supervivencia y el bienestar de los lechones. Fácil instalación gracias a su rosca estándar E27.',
            },
            {
                'categoria': 'EQUIPOS_COMPLEMENTARIOS',
                'subcategoria': None,
                'nombre': 'Bombilla infrarroja para precebo',
                'slug': 'bombilla-infrarroja-precebo',
                'orden': 87,
                'descripcion_corta': 'Bombilla infrarroja de 250 W para calefacción de precebo.',
                'descripcion': 'Bombilla infrarroja de alta potencia diseñada para proporcionar una fuente de calor uniforme en áreas de precebo, contribuyendo a mantener una temperatura adecuada para el bienestar y desarrollo de los lechones durante esta etapa.',
                'especificaciones': 'Voltaje: 220 V. Potencia: 250 W. Tipo: bombilla infrarroja de calor. Rosca: E27 estándar. Material: vidrio templado con reflector. Color de luz: infrarrojo (calor).',
                'aplicaciones': 'Calefacción en corrales de precebo. Proporciona un ambiente térmico estable para los lechones. Compatible con campanas o protectores para lámparas de calor.',
                'beneficios': 'Distribución uniforme del calor. Favorece el confort y el crecimiento de los animales. Bajo mantenimiento y fácil instalación.',
            },
        ]

        # Crear todos los productos
        count = 0
        for prod_data in productos:
            cat = cats[prod_data['categoria']]
            sub = subs.get(prod_data['subcategoria']) if prod_data.get('subcategoria') else None

            Producto.objects.create(
                categoria=cat,
                subcategoria=sub,
                nombre=prod_data['nombre'],
                slug=prod_data['slug'],
                descripcion_corta=prod_data['descripcion_corta'],
                descripcion=prod_data.get('descripcion', ''),
                materiales=prod_data.get('materiales', ''),
                capacidad=prod_data.get('capacidad', ''),
                dimensiones=prod_data.get('dimensiones', ''),
                regulacion=prod_data.get('regulacion', ''),
                componentes=prod_data.get('componentes', ''),
                aplicaciones=prod_data.get('aplicaciones', ''),
                beneficios=prod_data.get('beneficios', ''),
                especificaciones=prod_data.get('especificaciones', ''),
                imagen=f'img/productos/{cat.slug}/{prod_data["slug"]}/1.1.png',
                orden=prod_data['orden'],
                disponible=True,
                destacado=False,
            )
            count += 1

        self.stdout.write(self.style.SUCCESS(f'Se crearon {count} productos exitosamente.'))
