# Generated by Django 5.2.13 on 2026-07-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255)),
                ('icono', models.CharField(blank=True, help_text='Icono SVG o clase CSS', max_length=50)),
                ('imagen', models.CharField(blank=True, help_text='Ruta relativa de la imagen en static/', max_length=500, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden', 'pregunta'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('servicio_interes', models.CharField(blank=True, max_length=100)),
                ('leido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('periodo_ejecucion', models.CharField(blank=True, help_text='Ej: 2025, 2024-2026, Desde 2022', max_length=100)),
                ('tipo_trabajo', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('galeria', models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes adicionales')),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-destacado'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('beneficios', models.JSONField(blank=True, default=list)),
                ('icono', models.CharField(blank=True, help_text='Ruta de imagen en static/ o clase CSS', max_length=500)),
                ('imagen', models.CharField(blank=True, help_text='Ruta relativa de la imagen principal en static/', max_length=500, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('empresa', models.CharField(max_length=200)),
                ('trabajo_realizado', models.CharField(blank=True, max_length=300)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='ServicioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='La imagen se guardará automáticamente en static/img/servicios/', null=True, upload_to='')),
                ('imagen_ruta', models.CharField(blank=True, help_text='Ruta de imagen en static/ (alternativo a subir archivo)', max_length=500, null=True)),
                ('numero', models.CharField(blank=True, help_text='Número automático: 1.1, 1.2, 1.3...', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.servicio')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio',
                'verbose_name_plural': 'Imágenes de Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.CharField(blank=True, help_text='Ruta relativa de la imagen en static/', max_length=500, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('caracteristicas', models.JSONField(blank=True, default=list)),
                ('imagen', models.CharField(blank=True, help_text='Ruta relativa de la imagen, ej: img/productos/alimentacion/comederos/1.png', max_length=500, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.subcategoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', '-destacado', 'nombre'],
            },
        ),
    ]
