# Generated by Django 5.2.13 on 2026-07-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='galeria',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='La imagen se guardará automáticamente en static/img/proyectos/', null=True, upload_to='')),
                ('imagen_ruta', models.CharField(blank=True, help_text='Ruta de imagen en static/ (alternativo a subir archivo)', max_length=500, null=True)),
                ('numero', models.CharField(blank=True, help_text='Número automático: 1.1, 1.2, 1.3...', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de Proyecto',
                'verbose_name_plural': 'Imágenes de Proyectos',
                'ordering': ['orden'],
            },
        ),
    ]
