# Generated by Django 5.2.13 on 2026-07-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta relativa de la imagen principal, ej: img/productos/alimentacion/comederos/1.png', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='La imagen se guardará automáticamente en static/img/productos/', null=True, upload_to='')),
                ('imagen_ruta', models.CharField(blank=True, help_text='Ruta de imagen en static/ (alternativo a subir archivo)', max_length=500, null=True)),
                ('numero', models.PositiveIntegerField(default=0, help_text='Número de imagen within el producto')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['orden'],
            },
        ),
    ]
