# Generated by Django 5.2.13 on 2026-07-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_descripcion_corta_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta relativa de la imagen en static/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta relativa de la imagen, ej: img/productos/alimentacion/comederos/1.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta relativa de la imagen en static/', max_length=500, null=True),
        ),
    ]
