# Generated by Django 5.2.13 on 2026-07-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoria_imagen_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('beneficios', models.JSONField(blank=True, default=list)),
                ('icono', models.CharField(blank=True, help_text='Ruta de imagen en static/ o clase CSS', max_length=500)),
                ('imagen', models.CharField(blank=True, help_text='Ruta relativa de la imagen en static/', max_length=500, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
