# Generated by Django 5.2.13 on 2026-07-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoimagen',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen_ruta',
            field=models.CharField(blank=True, help_text='Ruta de imagen en static/ (ej: img/productos/alimentacion/comederos/1/1.1.png)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='numero',
            field=models.CharField(blank=True, help_text='Número automático: 1.1, 1.2, 1.3...', max_length=10),
        ),
    ]
