# Generated by Django 5.2.13 on 2026-07-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_productoimagen_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aplicaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='beneficios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='capacidad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='componentes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='dimensiones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='materiales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='regulacion',
            field=models.TextField(blank=True),
        ),
    ]
