# Generated by Django 5.2.13 on 2026-07-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_product_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(blank=True, help_text='La imagen se guardará automáticamente en static/img/productos/', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen_ruta',
            field=models.CharField(blank=True, help_text='Ruta de imagen en static/ (alternativo a subir archivo)', max_length=500, null=True),
        ),
    ]
